allowBuilds:
  sharp: true

# Notes on pnpm overrides:
#   BANDAID FIX: NuxtImg randomly broke. [Nov 2025]
#     Fix credits: @xiangshu233 – https://github.com/nuxt/image/issues/624#issuecomment-3004210513
#     Notes:
#       - Nuxt has been pretty painful, and I'm almost certain has caused way more trouble than the value it provides. 
#       - This lead me to investigate vanilla js and discover modern browser does everything that react/vue does with 50 lines of helper functions – See note `Idea - quote-unquote-framework` [Nov 2025]
#       - We could also remove NuxtImg. The only useful thing it seems to do is compress images (more than 10x on the color-spash images). But I could get even better compression using `pngquant --quality=65-80 color-splash-dark-1.png
#   Update: [Sep 2026] Moved overrides from package.json to pnpm-workspace.yaml because pnpm doesn't support the old way anymore.
overrides:
  ipx: "3.0.0"
